const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const {MeshoptSimplifier:M}=require('meshoptimizer');
function chunks(b){let a=0,r=[];while(a<b.length){assert(a+12<=b.length);let t=b.readUInt32LE(a),n=b.readUInt32LE(a+4),v=b.readUInt32LE(a+8);assert(a+12+n<=b.length);r.push({t,v,b:b.subarray(a+12,a+12+n)});a+=12+n;}return r;}
function pack(cs){return Buffer.concat(cs.map(c=>{let h=Buffer.alloc(12);h.writeUInt32LE(c.t);h.writeUInt32LE(c.b.length,4);h.writeUInt32LE(c.v,8);return Buffer.concat([h,c.b]);}));}
function readGeometry(cs){let entry=cs.find(c=>c.t==1);assert(entry,'Geometry Struct missing');let version=((entry.v>>>14)&0x3ff00)+0x30000|((entry.v>>>16)&0x3f);assert(version>=0x34000,'Old RenderWare geometry is unsupported');let raw=entry.b;let flags=raw.readUInt32LE(0),nt=raw.readUInt32LE(4),nv=raw.readUInt32LE(8),nm=raw.readUInt32LE(12);assert(!(flags&0x1000000)&&nm==1);let uvCount=(flags>>>16)&255; if(!uvCount)uvCount=flags&128?2:flags&4?1:0;let off=16,colorOff=off;if(flags&8)off+=nv*4;let uvOff=off;off+=nv*8*uvCount;let triOff=off;off+=nt*8;let morphOff=off;let hasPos=raw.readUInt32LE(off+16),hasNormals=raw.readUInt32LE(off+20);assert(hasPos);off+=24;let positions=new Float32Array(nv*3);for(let i=0;i<nv*3;i++)positions[i]=raw.readFloatLE(off+i*4);let uv=new Float32Array(nv*2);for(let i=0;i<nv*2&&uvCount;i++)uv[i]=raw.readFloatLE(uvOff+i*4);assert(off+nv*12+(hasNormals?nv*12:0)==raw.length,'Unexpected geometry payload');return {raw,flags,nt,nv,uvCount,triOff,morphOff,positions,uv,colorOff,uvOff,positionOff:off,hasNormals};}
function obj(p,geo,groups){let s='';for(let i=0;i<geo.nv;i++)s+=`v ${geo.positions[i*3]} ${geo.positions[i*3+1]} ${geo.positions[i*3+2]}\n`;for(const g of groups)for(let i=0;i<g.ids.length;i+=3)s+=`f ${g.ids[i]+1} ${g.ids[i+1]+1} ${g.ids[i+2]+1}\n`;fs.writeFileSync(p,s);}
const profiles={light:{ratio:.85,error:.005},medium:{ratio:.65,error:.015},strong:{ratio:.45,error:.035},lowpoly:{ratio:.25,error:.075}};
function geometryGroups(cs){const ext=cs.find(c=>c.t==3);assert(ext,'Geometry extensions missing');const es=chunks(ext.b);for(const e of es)assert([1294,39056121,287,39056120].includes(e.t),'Unsupported geometry plugin: '+e.t);
const bin=es.find(c=>c.t==1294);assert(bin&&bin.b.readUInt32LE(0)==0,'Only triangle-list Bin Mesh supported');let at=12,n=bin.b.readUInt32LE(4),groups=[];for(let i=0;i<n;i++){let length=bin.b.readUInt32LE(at),mat=bin.b.readUInt32LE(at+4);at+=8;assert(length%3==0);let ids=new Uint32Array(length);for(let j=0;j<length;j++)ids[j]=bin.b.readUInt32LE(at+j*4);at+=length*4;groups.push({mat,ids});}assert(at==bin.b.length);return {ext,es,bin,groups};}
function materialCount(cs){let list=cs.find(c=>c.t==8);assert(list);const st=chunks(list.b).find(c=>c.t==1);return st.b.readUInt32LE(0);}
function processDff(data,profile){let report={before:0,after:0,vertices:0,materials:0,geometries:0,maxError:0,preview:[],warnings:[]};const config=profiles[profile];
function transform(b){let cs=chunks(b);for(let c of cs){if(c.t==16||c.t==26)c.b=transform(c.b);else if(c.t==15){let gs=chunks(c.b),geo=readGeometry(gs),{ext,es,bin,groups}=geometryGroups(gs),mats=materialCount(gs);assert(geo.nv<=65535,'Too many vertices');for(let g of groups){assert(g.mat<mats&&g.ids.every(x=>x<geo.nv),'Invalid mesh indices');}assert(groups.reduce((n,g)=>n+g.ids.length/3,0)==geo.nt,'Triangle counts differ');
report.before+=geo.nt;report.vertices+=geo.nv;report.materials+=mats;report.geometries++;
let stride=geo.uvCount*2+4+(geo.hasNormals?3:0),attrs=new Float32Array(geo.nv*stride),weights=[];for(let i=0;i<geo.uvCount*2;i++)weights.push(20);weights.push(1,1,1,1);if(geo.hasNormals)weights.push(1,1,1);assert(stride<=32);
for(let i=0;i<geo.nv;i++){let at=i*stride;for(let u=0;u<geo.uvCount;u++){attrs[at++]=geo.raw.readFloatLE(geo.uvOff+u*geo.nv*8+i*8);attrs[at++]=geo.raw.readFloatLE(geo.uvOff+u*geo.nv*8+i*8+4);}for(let j=0;j<4;j++)attrs[at++]=(geo.flags&8)?geo.raw[geo.colorOff+i*4+j]/255:1;if(geo.hasNormals)for(let j=0;j<3;j++)attrs[at++]=geo.raw.readFloatLE(geo.positionOff+geo.nv*12+i*12+j*4);}
let updated=groups.map(g=>{if(!config||g.ids.length<60)return g;let [ids,error]=M.simplifyWithAttributes(g.ids,geo.positions,3,attrs,stride,weights,null,Math.max(3,Math.floor(g.ids.length*config.ratio/3)*3),config.error,['LockBorder','ErrorAbsolute']);assert(ids.length&&ids.length<=g.ids.length&&ids.length%3==0&&ids.every(x=>x<geo.nv));report.maxError=Math.max(report.maxError,error);return {mat:g.mat,ids};});
let count=updated.reduce((n,g)=>n+g.ids.length/3,0);report.after+=count;
// Preview each geometry separately: no incorrect assembly without Frame transforms.
if(report.preview.length<8){let tris=[];let flat=updated.flatMap(g=>{let a=[];for(let i=0;i<g.ids.length;i+=3)a.push([g.ids[i],g.ids[i+1],g.ids[i+2]]);return a;});let step=Math.max(1,Math.ceil(flat.length/1800));for(let i=0;i<flat.length;i+=step)tris.push(flat[i].map(v=>Array.from(geo.positions.subarray(v*3,v*3+3))));report.preview.push({triangles:tris,total:flat.length});}
if(config){let triangles=Buffer.alloc(count*8),to=0;for(let g of updated)for(let i=0;i<g.ids.length;i+=3){triangles.writeUInt16LE(g.ids[i+1],to);triangles.writeUInt16LE(g.ids[i],to+2);triangles.writeUInt16LE(g.mat,to+4);triangles.writeUInt16LE(g.ids[i+2],to+6);to+=8;}
let head=Buffer.from(geo.raw.subarray(0,geo.triOff));head.writeUInt32LE(count,4);gs.find(c=>c.t==1).b=Buffer.concat([head,triangles,geo.raw.subarray(geo.morphOff)]);
let h=Buffer.alloc(12);h.writeUInt32LE(updated.length,4);h.writeUInt32LE(count*3,8);bin.b=Buffer.concat([h,...updated.map(g=>{let b=Buffer.alloc(8+g.ids.length*4);b.writeUInt32LE(g.ids.length);b.writeUInt32LE(g.mat,4);for(let i=0;i<g.ids.length;i++)b.writeUInt32LE(g.ids[i],8+i*4);return b;})]);ext.b=pack(es);c.b=pack(gs);
let check=readGeometry(chunks(c.b));assert(check.raw.subarray(16,check.triOff).equals(geo.raw.subarray(16,geo.triOff)));assert(check.raw.subarray(check.morphOff+check.nt*0).equals(geo.raw.subarray(geo.morphOff)));}
}}return pack(cs);}const output=transform(data);assert(report.geometries>0,'No supported geometry');report.bytesBefore=data.length;report.bytesAfter=output.length;report.reduction=100*(1-report.after/report.before);report.warnings=['Vertex buffer retained: triangle reduction is not equivalent RAM reduction.','Per-material boundaries locked. Target ratio may not be reached.','Preview is sampled, untextured local geometry; validate exported file in MTA.'];return {output,report};}
function inspectOther(data,ext){if(ext=='.col'){let at=0,models=[];while(at<data.length){assert(at+32<=data.length);let magic=data.toString('ascii',at,at+4);assert(['COLL','COL2','COL3','COL4'].includes(magic));let len=data.readUInt32LE(at+4)+8;assert(len>=32&&at+len<=data.length);models.push({format:magic,name:data.toString('ascii',at+8,at+30).split('\0')[0],bytes:len});at+=len;}return {type:'COL',models,bytes:data.length,note:'Inspection only. Collision simplification is not performed.'};}
assert(ext=='.txd','Select a DFF, COL or TXD file');let textures=[];function walk(b,parent){for(let c of chunks(b)){if(c.t==22||c.t==21)walk(c.b,c.t);if(parent==21&&c.t==1){assert(c.b.length>=88);let platform=c.b.readUInt32LE(0);assert(platform==8||platform==9,'Only PC D3D8/9 TXD inspection supported');textures.push({name:c.b.toString('ascii',8,40).split('\0')[0],width:c.b.readUInt16LE(80),height:c.b.readUInt16LE(82),depth:c.b[84],mips:c.b[85]});}}}walk(data,0);return {type:'TXD',textures,bytes:data.length,note:'Inspection only; no recompression or resizing.'};}
async function main(req){await M.ready;let input=path.resolve(req.input),data=fs.readFileSync(input),ext=path.extname(input).toLowerCase();assert(data.length<256*1024*1024,'File exceeds 256 MiB');if(ext!='.dff')return inspectOther(data,ext);
assert(!req.profile||profiles[req.profile],'Unknown profile');let {output,report}=processDff(data,req.profile);report.type='DFF';report.input=input;
if(req.profile){assert(req.output,'Output required');let target=path.resolve(req.output);assert(target.toLowerCase()!=input.toLowerCase(),'Original cannot be overwritten');assert(!fs.existsSync(target),'Output already exists');const verified=processDff(output,null).report;assert(verified.before==report.after&&verified.vertices==report.vertices);report.sha256=crypto.createHash('sha256').update(output).digest('hex');fs.writeFileSync(target,output,{flag:'wx'});report.output=target;}
return report;}
if(require.main===module){let data='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>data+=c);process.stdin.on('end',async()=>{try{process.stdout.write(JSON.stringify(await main(JSON.parse(data))));}catch(e){process.stderr.write(e.message);process.exitCode=1;}});}
module.exports={main,processDff,chunks};
